# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mnmlyf
tagline:             Minimal lifestyle blog
url:                 http://mnmlyf.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ganesh Khade
  url:               https://twitter.com/mnmlyf
  email:             mnmlyf@gmail.com

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-66234781-1'

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/mnmlyf/mnmlyf
